import requests

BASE = "http://127.0.0.1:5000/"

response = requests.put(BASE + "post/1", {"userId": 1, "title": "Some title", "body": "Some body"})
print(response.json())
input()
response = requests.put(BASE + "post/2", {"userId": 1, "title": "Some title 2", "body": "Some body 2"})
print(response.json())
input()
response = requests.put(BASE + "post/3", {"userId": 1, "title": "Some title", "body": "Some body"})
print(response.json())
input()
response = requests.put(BASE + "post/4", {"userId": 1, "title": "Some title", "body": "Some body"})
print(response.json())
input()
response = requests.get(BASE + "post/1")
print(response.json())
input()
response = requests.get(BASE + "post/6")
print(response.json())
input()
response = requests.delete(BASE + "post/1")
print(response.json())
input()
response = requests.patch(BASE + "post/2", {'body': "New body"})
print(response.json())
input()
response = requests.get(BASE + "post/0", {'userId': 1})
print(response.json())